
language: python

install:
  - sudo apt-get update
  # We do the miniconda download conditionally because it saves us some
  # time if the version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Get some basic packages
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
  # OK, we now have conda python!
  # Do the requirements next - some redundancy?
  - pip install -r requirements.txt
  - pip install git+git://github.com/tholoien/XDGMM.git#egg=xdgmm
  - python setup.py install
  # We need nbconvert to run the notebooks
  - pip install nbconvert

script:
  - nosetests
  - jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute Notebooks/Demo.ipynb
