
language: python

install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install git+git://github.com/tholoien/XDGMM.git#egg=xdgmm
  - python setup.py install

script:
  - nosetests
